FROM golang:1.12

# copy full source tree
WORKDIR /go/src/github.com/ilove/event-sourcing-kafka
COPY . .

# build
WORKDIR src/eventservice
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o eventservice

FROM scratch

# copy binary
COPY --from=0 /go/src/github.com/ilovejs/event-sourcing-kafka/src/eventservice/eventservice /eventservice
ENV LISTEN_URL=0.0.0.0:8181
EXPOSE 8181
CMD ["/eventservice"]